#cloud-config
apt:
    sources:
        docker.list:
            source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
            keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true
package_upgrade: true

groups:
    - docker

write_files:
    -   path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
        content: |
            net.ipv4.conf.all.forwarding=1

system_info:
    default_user:
        groups: [ docker ]

users:
    name: zymat
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICZVfEr6eaopNH+V3e4yOwywdiQt9HNiE9zvWtFmdfpi
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOslya+KlMziz+0j0mJUbtwuxMvgb2I+5Bv0WH3+6w8s
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKgHL6Evp0LXPmpxblsFW6VwPH00TcoA3D5Jgv1FOkdk

packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - git
    - ufw
    - fail2ban

runcmd:
    - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
    - systemctl enable fail2ban
    - ufw allow OpenSSH
    - ufw enable
    - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)KbdInteractiveAuthentication/s/^.*$/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)ChallengeResponseAuthentication/s/^.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
    - sed -i '$a AllowUsers holu' /etc/ssh/sshd_config
    - git clone https://github.com/Gustav2/zymat_devops.git /home/zymat/zymat_devops
    - reboot