#cloud-config
groups:
    - docker

users:
    -   name: root
        lock_passwd: true
    -   name: zymat
        groups: users, admin, docker
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOslya+KlMziz+0j0mJUbtwuxMvgb2I+5Bv0WH3+6w8s gustavnybro@hackerman-desktop
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICZVfEr6eaopNH+V3e4yOwywdiQt9HNiE9zvWtFmdfpi gustavnybro@hackerman-laptop
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKgHL6Evp0LXPmpxblsFW6VwPH00TcoA3D5Jgv1FOkdk dani@Daniel-Desktop

chpasswd:
    expire: false

packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - git
    - debian-keyring
    - debian-archive-keyring

runcmd:
    - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
    - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
    - sed -i '$a AllowUsers zymat' /etc/ssh/sshd_config
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt-get update -y
    - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    - systemctl start docker
    - systemctl enable docker
    - git clone https://github.com/Gustav2/zymat_devops.git /home/zymat/zymat_devops
    - chown -R zymat:zymat /home/zymat/zymat_devops
    - mkdir /home/zymat/.docker
    - cp /home/zymat/zymat_devops/config.json /home/zymat/.docker/config.json
    - chown -R zymat:zymat /home/zymat/.docker
    - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
    - sudo apt update
    - sudo apt install caddy
    - caddy run --config /home/zymat/zymat_devops/Caddyfile

power_state:
    mode: reboot
    condition: True