#cloud-config
groups:
    - docker

users:
    -   name: root
        lock_passwd: true
    -   name: zymat
        groups: users, admin, docker
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOslya+KlMziz+0j0mJUbtwuxMvgb2I+5Bv0WH3+6w8s gustavnybro@hackerman-desktop

chpasswd:
    expire: false

packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - git

runcmd:
    - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
    - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
    - sed -i '$a AllowUsers zymat' /etc/ssh/sshd_config
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt-get update -y
    - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    - systemctl start docker
    - systemctl enable docker
    - git clone https://github.com/Gustav2/zymat_devops.git /home/zymat/zymat_devops

power_state:
    mode: reboot
    condition: True