name: zymat_frontend

services:
    zymat_frontend:
        container_name: zymat_frontend
        image: ghcr.io/zymat-dk/zymat_frontend:main
        ports:
            - "3000:3000"

        environment:
            - NEXT_SHARP_PATH=/tmp/node_modules/sharp

        env_file:
            -  .env

        restart: always

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/zymat/.docker/config.json:/config.json
        command: --interval 30